program = declaration* EOF ;

declaration = varDecl
            | printStmt ;

varDecl   = "var" IDENTIFIER ( "=" expression )? ";" ;
statement = exprStmt
          | printStmt ;

exprStmt  = expression ";" ;
printStmt = "print" expression ";" ;

expression = equality ;

equality       = comparison ( ( "==" | "!=" ) comparison )* ;
comparison     = additive ( ( "<" | "<=" | ">" | ">=" ) additive )* ;
additive       = multiplicative ( ("-" | "+") multiplicative )* ;
multiplicative = unary ( ("/" | "*") unary )* ;

unary          = ( "-" | "!" ) unary
               | primary ;
primary        = literal | grouping | IDENTIFIER ;
grouping       = "(" expression ")" ;
literal        = NUMBER | STRING | "true" | "false" | "nil"

