program = statement* EOF ;

statement = exprStmt
          | printStmt ;

exprStmt  = expression ";" ;
printStmt = "print" expression ";" ;

expression = ( equality )? ;

equality       = comparison ( ( "==" | "!=" ) comparison )* ;
comparison     = additive ( ( "<" | "<=" | ">" | ">=" ) additive )* ;
additive       = multiplicative ( ("-" | "+") multiplicative )* ;
multiplicative = unary ( ("/" | "*") unary )* ;

unary          = ( "-" | "!" ) unary
               | primary ;
primary        = literal | grouping ;
grouping       = "(" expression ")" ;
literal        = NUMBER | STRING | "true" | "false" | "nil"

